import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#F8F8F8',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 20,
    marginTop: 30,
    color: '#222',
  },
  status: {
    fontSize: 16,
    color: '#444',
    textAlign: 'center',
    marginBottom: 10,
  },
  button: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 5,
    marginVertical: 10,
    width: 240,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    marginTop: 10,
    elevation: 3,
  },
  buttonText: {
    fontSize: 16,
    color: '#FFF',
    fontWeight: '600',
  },
  transcriptionContainer: {
    marginTop: 10,
    padding: 20,
    width: '100%',
  },
  transcriptionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 20,
    marginTop: 5,
    textAlign: 'center',
  },
  agentTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 5,
    marginTop: 5,
    textAlign: 'center',
  },
  transcriptionTextInput: {
    width: 280,
    height: 130,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    backgroundColor: '#fff',
    color: '#333',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    minHeight: 120,
    textAlignVertical: 'top',
    backgroundColor: '#f9f9f9',
  },
  durationText: {
    fontSize: 14,
    color: '#666',
    marginTop: 8,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  dropdownWrapper: {
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 10,
    backgroundColor: '#fff',
    width: 300,
    height: 60,
    justifyContent: 'center',
    paddingHorizontal: 1,
    alignSelf: 'center',
    marginTop: 10,
  },
  picker: {
    height: 60,
    width: '100%',
    color: '#333',
  },
  speakButton: {
    marginVertical: 10,
    marginBottom: -5,
    borderRadius: 5,
    overflow: 'hidden',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
});
